### ISSUE TITLE
Auto fit video

### ISSUE THREAD

**Issue by JulienMontfort** [sabitertan/BlazorBarcodeScanner#48]
Hello, your project is great, 

Is it possible to set de width of video to 100% instead of int value ?

Thank you.

**Comment by IDGC-ESC** [comment]
In case nobody else sees this for a while, the best workaround I can find is to update the <video>'s width and height attributes from JS after it's rendered:
```js
function setVideoWidthMax() {
    var element = document.querySelector('.zxing-video-container video[height][width]');
    if (element) {
        var parent = document.querySelector('.zxing-video-container');
        var width = Math.max(Math.round(Math.min(element.videoWidth, parent.offsetWidth) * (2 / 3)), 200);
        var height = Math.max(Math.round(Math.min(element.videoHeight, parent.offsetWidth) * (2 / 3)), 200);
        if (width > height)
            width = height;
        element.setAttribute('width', width);
        element.setAttribute('height', height);
    }
}
```
Of course, from the Razor page, you'll `@inject IJSInProcessRuntime JS` and then call `JS.InvokeVoid("setVideoWidthMax");` to apply the resize.
I'm sure there's a better way out there or that the dev could add one, but this appears to size the video to fit in the viewport, often with a little bit of padding.
Updating video.width alone does not modify it, as the actual rendered width is restricted by its height and vice versa, so that's why I have some calculations in there. Hope it helps

**Comment by sabitertan** [comment]
Thanks for suggestion, this feature added in 1.0.2, have a look at FullWitdh example at the repo for implementation.
https://github.com/sabitertan/BlazorBarcodeScanner/blob/v1.0.2/BlazorZXingJSApp/Client/Pages/FullWidthVideoExample.razor

**Comment by JulienMontfort** [comment]
Great, the enhancement work as needed.
Thank you !
