### ISSUE TITLE
Barcodes Not working

### ISSUE THREAD

**Issue by shannonslaton** [sabitertan/BlazorBarcodeScanner#49]
This is fantastic.  I was able to get this to work in my application very easily.  It scans QR codes perfectly, but not barcodes.  I tried with this barcode:

https://www.publicdomainpictures.net/en/view-image.php?image=15705&picture=barcode&large=1

It doesn't work on your demo or in my project.  I went to the link for formats and it worked on that site:

https://zxing-js.github.io/library/examples/multi-camera/

Any thoughts?

**Comment by IDGC-ESC** [comment]
I am also encountering this issue. Works great for QR codes and, with a bit of finagling, Code-39 and EAN-13... Can't for the life of me get it to scan a single UPC-A though.

**Comment by shannonslaton** [comment]
Glad to know I'm not alone.  

Have you tried here:
https://zxing-js.github.io/library/examples/multi-camera/

I can scan a barcode on that website and it works every time.  Wish I could figure out why.

**Comment by IDGC-ESC** [comment]
Found a workaround!
Looks like the problem is with the provided zxingjs file and the latest version actually works!
Replace:
```html
<script src="_content/BlazorBarcodeScanner.ZXing.JS/zxingjs.index.min.js"></script>
```
with:
```html
<script src="https://unpkg.com/@zxing/library@latest/umd/index.min.js"></script>
```

See if that works for you as well and, if it does, we can simply suggest this reference be updated in the project to either a static copy of the working file (per current implementation) or an update to the implementation instructions to pull latest instead of using the static file.

**Comment by shannonslaton** [comment]
That's great!  Hopefully we can get an updated version.

**Comment by IDGC-ESC** [comment]
@sabitertan -- See above, but it looks like the implemented zxing-js is outdated and has issues with scanning UPC-A. Updating to the latest corrects the problem.
