### ISSUE TITLE
Not threadsafe

### ISSUE THREAD

**Issue by horrorhound** [sabitertan/BlazorBarcodeScanner#59]
When using Blazor Server with multiple devices at once the "OnBarcodeReceived" event is raised for all devices on a scan which then throws the following exception on the secondary device.

The current thread is not associated with the Dispatcher. Use InvokeAsync() to switch execution to the Dispatcher when triggering rendering or component state. 

```
<BlazorBarcodeScanner.ZXing.JS.BarcodeReader Title="Scan Barcode from Camera"
@ref="_reader"
 
                                             StartCameraAutomatically="false"
                                             OnBarcodeReceived="OnBarcodeScan"
                                             ShowStart="false"
                                             ShowReset="false"
                                             ShowToggleTorch="false"
                                             FullWidthVideo="true"
                                             ShowVideoDeviceList="true"
                                             StreamWidth="@_streamWidth"
                                             StreamHeight="@_streamHeight" />


private BarcodeReader _reader;
```

I can't find anything on my page (which is pretty simple) that could cause OnBarcodeScan to execute on the secondary device (as if the scanner is declared as a singleton)...

**Comment by KeesAlderliesten** [comment]
The problem is that static classes and static functions are used. A comment in the JsInteropClass.cs states: 'Unfortunately JS is unable to invoke public methods of internal classes. Thus we route the call to the internal class at this point.'
But that is not true, Microsoft docs show how to call functions in instance classes (https://learn.microsoft.com/en-gb/aspnet/core/blazor/javascript-interoperability/call-dotnet-from-javascript?view=aspnetcore-6.0#class-instance-examples). You have to pass a reference to that instance to javascript, and then use a JS helper class to call the methods in the instance class.
